import type { Metadata } from "next";
import "./globals.css";
import "./main.scss";
import { Analytics } from "@vercel/analytics/react"
import { Providers } from './providers';



export const metadata: Metadata = {
  title: "MAK Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
       <meta name="viewport" content="width=device-width, initial-scale=1" />
      <body
        className=""
      >
        <Providers>{children}</Providers>
        <Analytics />
      </body>
    </html>
  );
}
